on:
  pull_request:
    branches:
      - feature/**
      - master
jobs:
 get-commit-id:
  runs-on: ubuntu-latest
  outputs:
    text: ${{ steps.get_head_commit_title.outputs.title }}
  steps:
    - name: Get repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
    - id: get_head_commit_title
      run: echo "title=$(git log --format=%B -n 1 HEAD | head -n 1)" >> $GITHUB_OUTPUT