on:
  pull_request:

jobs:
  get_pr_title:
    name: get_pr_title
    runs-on: ubuntu-latest
    outputs: 
      body: ${{ steps.description.outputs.body }}
    env:
      title: ${{ github.event.pull_request.title }}
      body: ${{ github.event.pull_request.body }}
    steps:
      - name: Print Title of PR
        run: echo "Title  = ${{ env.title }}"
      - name: Print Body of PR
        id: description
        run: echo "::set-output name=body::${{ env.body }}"

  get_folder_path:
    name: get_folder_path
    needs: get_pr_title
    runs-on: ubuntu-latest
    if: startsWith(needs.get_pr_title.outputs.body, 'RUNE2E')
    steps:
      - name: Echo PR Body
        run: echo "PR Body = ${{ needs.get_pr_title.outputs.body }}"
      - name: Split description
        run: |
          IFS='-' read -r Var1 Var2 <<< "${{ needs.get_pr_title.outputs.body }}"
          echo "Part 1: $Var1"
          echo "Part 2: $Var2"
          echo "::set-output name=Var2::$Var2"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Debug Var2
        run: echo "Var2 = ${{ needs.get_folder_path.outputs.Var2 }}"
      - name: Run Playwright tests
        run: npx playwright test  ${{ needs.get_folder_path.outputs.Var2 }} --project chromium
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
