on:
  push:
    
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    env: 
       commitmsg: "rune2e_src/test"

    steps:
      - name: "split msg"
        run: |
         var2 = env.commitmsg | cut -f2 -d-
         echo "varible is $var2"
