on:
  pull_request:

jobs:
  get_pr_title:
    name: get_pr_title
    runs-on: ubuntu-latest
    outputs: 
      body: ${{ steps.description.outputs.body }}
    env:
      title: ${{ github.event.pull_request.title }}
      body: ${{ github.event.pull_request.body }}
    steps:
      - name: Print Title of PR
        run: echo "Title  = ${{ env.title }}"
      - name: Print Body of PR
        id: description
        run: echo "::set-output name=body::${{ env.body }}"

  get_folder_path:
    name: get_folder_path
    needs: get_pr_title
    runs-on: ubuntu-latest
    outputs:
      path: ${{ steps.get_path.outputs.path }}
    if: startsWith(needs.get_pr_title.outputs.body, 'RUNE2E')
    steps:
      - name: Echo PR Body
        run: echo "PR Body = ${{ needs.get_pr_title.outputs.body }}"
      - name: Split description
        id: get_path
        run: |
          IFS='-' read -r Var1 Var2 <<< "${{ needs.get_pr_title.outputs.body }}"
          echo "Part 1: $Var1"
          echo "Part 2: $Var2"
          echo "::set-output name=path::$Var2"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Debug path
        run: echo "path = ${{ steps.get_path.outputs.path }}"        
      - name: Run Playwright tests
        run: npx playwright test ${{ steps.get_path.outputs.path }} --project chromium
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  check_commit_msg:
    name: check_commit_msg
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
    steps:
    - name: get repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Print head git commit message 
      id: get_head_commit_message
      run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"

  e2e_test:
    name: E2E tests
    needs: check_commit_msg
    if: ${{ contains(needs.check_commit_msg.outputs.head-commit-message, 'e2e') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
