name: Dev deploy

on:
    
  pull_request:
      types: [opened, reopened, edited, synchronize]

jobs:
  deploy-to-dev:
      name: deploy to dev
      runs-on: ubuntu-22.04
      steps:

        - name: checkout repo
          uses: actions/checkout@v3

        - name: Set env var
          run: |
            echo commit=$(git log --format=%B -n 1) >> $GITHUB_ENV