on:
  push:
    
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    env: 
       commitmsg: "rune2e_src/test"
       var2: ""

    steps:
      - name: "split msg"
        run: |
         var2=$(echo ${{env.commitmsg}} | cut -f2 -d-)
         echo "varible is ${{env.var2}}"
